//! Token-budget stop conditions (crosslink #590, CC parity with
//! `query/tokenBudget.ts`).
//!
//! This module owns the declarative schema and the predicate that maps
//! cumulative token spend onto a typed [`StopReason`]. The pipeline turn
//! loop is the consumer — it accumulates per-turn deltas into a
//! session-scoped counter and calls [`StopConditionsConfig::is_met`]
//! after every assistant response.
//!
//! The schema is intentionally narrow in this first pass: only token-budget
//! limits are wired. CC's `query/tokenBudget.ts` additionally tracks
//! per-tool-call rate limits and elapsed-wallclock guards; those land
//! alongside their own consumers and are tracked as follow-up issues.
//!
//! Why split this out from `session/`: the predicate has zero session
//! state of its own — it is a pure function of `(config, totals)`. Living
//! under `config/` keeps the serde surface adjacent to the rest of the
//! YAML schema and lets the pipeline import only the predicate without
//! pulling in session internals.

use serde::{Deserialize, Serialize};

/// Optional caps on cumulative token spend for a single session.
///
/// A `None` field means "no cap on this dimension"; a `Some(n)` field
/// means "stop the turn loop the first time cumulative spend in that
/// bucket exceeds `n`". The fields are deliberately independent so a
/// caller can budget input and output separately.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct StopConditionsConfig {
    /// Hard cap on cumulative *input* tokens across all turns in the
    /// session. Includes cached and uncached prompt tokens.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_total_input_tokens: Option<u64>,
    /// Hard cap on cumulative *output* tokens emitted by the model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_total_output_tokens: Option<u64>,
    /// Hard cap on cumulative *combined* spend (input + output). Useful
    /// for budgeting against a flat $/token rate where the input/output
    /// distinction does not matter.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_total_tokens: Option<u64>,
}

/// Cumulative token spend, supplied by the caller (typically derived
/// from the pricing layer's `cost_tracked` accumulator — see crosslink
/// #649 and [`crate::session::pricing`]).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct TokenTotals {
    /// Cumulative input tokens (prompt + cached prefill).
    pub input: u64,
    /// Cumulative output tokens (generated by the model).
    pub output: u64,
}

impl TokenTotals {
    /// Total combined spend across input and output.
    #[must_use]
    pub const fn combined(self) -> u64 {
        self.input.saturating_add(self.output)
    }
}

/// Why the turn loop must stop. Each variant corresponds 1:1 to a cap
/// in [`StopConditionsConfig`] so the caller can render a human-readable
/// abort message without re-deriving which limit triggered.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    /// `max_total_input_tokens` was crossed.
    InputTokenBudget,
    /// `max_total_output_tokens` was crossed.
    OutputTokenBudget,
    /// `max_total_tokens` (combined) was crossed.
    TotalTokenBudget,
}

impl StopReason {
    /// Stable identifier for log / event emission. Matches the `snake_case`
    /// rendering of the serde variant name so an emitted event field and
    /// the rendered enum agree byte-for-byte.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::InputTokenBudget => "input_token_budget",
            Self::OutputTokenBudget => "output_token_budget",
            Self::TotalTokenBudget => "total_token_budget",
        }
    }
}

impl StopConditionsConfig {
    /// Test whether `totals` crosses any configured cap. Returns the first
    /// matching [`StopReason`] (priority order: input → output → total) so
    /// the caller's abort message is deterministic.
    ///
    /// Returns `None` when no caps are configured or when `totals` is
    /// within every configured cap.
    #[must_use]
    pub const fn is_met(&self, totals: TokenTotals) -> Option<StopReason> {
        if let Some(cap) = self.max_total_input_tokens {
            if totals.input > cap {
                return Some(StopReason::InputTokenBudget);
            }
        }
        if let Some(cap) = self.max_total_output_tokens {
            if totals.output > cap {
                return Some(StopReason::OutputTokenBudget);
            }
        }
        if let Some(cap) = self.max_total_tokens {
            if totals.combined() > cap {
                return Some(StopReason::TotalTokenBudget);
            }
        }
        None
    }

    /// True when no caps are configured. Convenience for the pipeline
    /// to short-circuit the predicate when the user hasn't opted in.
    #[must_use]
    pub const fn is_inactive(&self) -> bool {
        self.max_total_input_tokens.is_none()
            && self.max_total_output_tokens.is_none()
            && self.max_total_tokens.is_none()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_config_is_inactive() {
        let cfg = StopConditionsConfig::default();
        assert!(cfg.is_inactive());
        assert!(
            cfg.is_met(TokenTotals {
                input: u64::MAX,
                output: u64::MAX,
            })
            .is_none(),
            "inactive config must never trip even on absurd totals"
        );
    }

    #[test]
    fn input_budget_trips_first() {
        let cfg = StopConditionsConfig {
            max_total_input_tokens: Some(100),
            max_total_output_tokens: Some(100),
            max_total_tokens: Some(100),
        };
        let totals = TokenTotals {
            input: 101,
            output: 101,
        };
        // Input has highest priority in the cascade.
        assert_eq!(cfg.is_met(totals), Some(StopReason::InputTokenBudget));
    }

    #[test]
    fn output_budget_trips_when_input_under() {
        let cfg = StopConditionsConfig {
            max_total_input_tokens: Some(1_000),
            max_total_output_tokens: Some(100),
            max_total_tokens: None,
        };
        let totals = TokenTotals {
            input: 50,
            output: 200,
        };
        assert_eq!(cfg.is_met(totals), Some(StopReason::OutputTokenBudget));
    }

    #[test]
    fn total_budget_trips_when_components_under_their_caps() {
        let cfg = StopConditionsConfig {
            max_total_input_tokens: Some(1_000),
            max_total_output_tokens: Some(1_000),
            max_total_tokens: Some(500),
        };
        let totals = TokenTotals {
            input: 400,
            output: 200,
        };
        assert_eq!(cfg.is_met(totals), Some(StopReason::TotalTokenBudget));
    }

    #[test]
    fn boundary_at_exact_cap_does_not_trip() {
        let cfg = StopConditionsConfig {
            max_total_input_tokens: Some(100),
            ..Default::default()
        };
        let totals = TokenTotals {
            input: 100,
            output: 0,
        };
        assert!(
            cfg.is_met(totals).is_none(),
            "predicate must use strict `>` so exactly-at-cap is still allowed"
        );
    }

    #[test]
    fn combined_saturates_on_overflow() {
        // saturating_add prevents pathological wrap-around.
        let t = TokenTotals {
            input: u64::MAX,
            output: 1,
        };
        assert_eq!(t.combined(), u64::MAX);
    }

    #[test]
    fn stop_reason_as_str_matches_serde_render() {
        for r in [
            StopReason::InputTokenBudget,
            StopReason::OutputTokenBudget,
            StopReason::TotalTokenBudget,
        ] {
            let serde_rendered = serde_json::to_string(&r).unwrap();
            // serde wraps strings in quotes.
            let expected = format!("\"{}\"", r.as_str());
            assert_eq!(serde_rendered, expected);
        }
    }

    #[test]
    fn schema_round_trips_through_yaml() {
        let cfg = StopConditionsConfig {
            max_total_input_tokens: Some(1),
            max_total_output_tokens: None,
            max_total_tokens: Some(2),
        };
        let yaml = serde_yaml::to_string(&cfg).unwrap();
        let back: StopConditionsConfig = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(cfg, back);
        assert!(
            !yaml.contains("max_total_output_tokens"),
            "None fields must be skipped on serialize"
        );
    }
}
